// Kunskapsbasen för textförståelsen: hundratals svenska formuleringar om varje sakfråga (med riktning),
// ton, attityd och känslor. Matchas mot det spelaren skriver med teckentrigram (ai/ngram.js) och,
// om spelaren slagit på det, med inbäddningar på enheten (ai/embed.js). Policyområdena och
// statistikens namn läggs till automatiskt.
import { POLICIES } from '../data/policies.js';
import { STATS } from '../data/stats.js';

// L = vänster/mjuk/öppen riktning på axeln, R = höger/stram/hård, N = ämnet utan riktning
export const KB_ISSUES = {
  ekonomi: {
    L: ['höj skatten för de rika', 'de som tjänar mest ska bidra mer', 'omfördela från rika till fattiga', 'mer pengar till välfärden i stället för skattesänkningar', 'klyftorna växer och det måste stoppas', 'återinför förmögenhetsskatten', 'höjd kapitalskatt', 'bankerna ska betala mer skatt', 'skattesänkningar för de rika betalas av vanligt folk', 'staten måste ta större ansvar för ekonomin', 'låna till investeringar i stället för att spara', 'rättvis fördelning av pengarna', 'de rika blir rikare medan vanligt folk får mindre', 'vi behöver en starkare gemensam sektor', 'höj skatten på vinster och arv', 'inkomstskillnaderna är för stora', 'mer till välfärden, mindre till miljardärerna', 'överskottsmålet är för strikt, låt staten investera', 'avdragen gynnar bara höginkomsttagare', 'ta tillbaka pengarna från skatteparadisen'],
    R: ['sänk skatten på arbete', 'folk ska få behålla mer av sin lön', 'lägre skatter ger fler jobb', 'mindre stat och mer frihet för individen', 'sänkt bolagsskatt för att locka företag', 'skattetrycket är för högt i sverige', 'avreglera och minska byråkratin', 'privata företag driver välfärden bättre än staten', 'ordning och reda i statsfinanserna', 'slösa inte med skattebetalarnas pengar', 'sänk momsen', 'höj brytpunkten för statlig skatt', 'ett lägre skattetryck lockar investeringar', 'företagen skapar jobben, inte politikerna', 'sänk arbetsgivaravgifterna', 'det ska löna sig att arbeta', 'bidragstaket måste sänkas', 'skär i de offentliga utgifterna', 'skattesänkningar ger tillväxt', 'minska statens inblandning i ekonomin'],
    N: ['folk har inte råd med maten längre', 'matpriserna har skenat', 'inflationen urholkar lönerna', 'räntorna slår hårt mot hushållen', 'hushållens ekonomi är pressad', 'statsskulden', 'budgetunderskottet', 'tillväxten i ekonomin', 'bruttonationalprodukten', 'lågkonjunkturen slår mot jobben', 'priserna på allt har gått upp', 'plånboksfrågor', 'ekonomin går på knäna', 'räntan och bolånen', 'konjunkturen vänder', 'investeringar i infrastruktur och industri', 'finansieringen av reformen', 'budgeten för nästa år', 'skatteintäkterna', 'elräkningen och matkassen äter upp lönen', 'pensionärerna har inte råd', 'barnfamiljerna får det allt tuffare', 'hur ska det betalas', 'var ska pengarna komma ifrån', 'kostar miljarder'],
  },
  migration: {
    L: ['sverige ska ta emot människor på flykt', 'rätten till asyl är helig', 'en human flyktingpolitik', 'familjer ska få återförenas', 'integration genom jobb och språk, inte genom straff', 'invandringen berikar sverige', 'vi behöver arbetskraftsinvandring', 'stoppa utvisningarna av barn', 'papperslösa ska få vård', 'öppna hjärtan', 'bemöt nyanlända med respekt', 'det är inte invandrarnas fel', 'rasismen är problemet, inte invandringen', 'alla människor har lika värde oavsett ursprung', 'sverige klarar att hjälpa fler', 'ge de som flytt en chans', 'sänk inte flyktingkvoten', 'ett generöst mottagande'],
    R: ['invandringen måste minska kraftigt', 'stäng gränsen', 'stoppa asylinvandringen', 'utvisa fler som begått brott', 'ställ krav på dem som kommer hit', 'språkkrav för medborgarskap', 'bidrag ska inte gå till nyanlända', 'sverige har tagit emot för många', 'integrationen har misslyckats', 'skärpta regler för anhöriginvandring', 'återvandring för dem som inte anpassar sig', 'volymerna måste ned', 'utanförskapet växer i förorterna på grund av invandringen', 'hårdare gränskontroller', 'inget medborgarskap utan egen försörjning', 'asylsökande ska bo i transitcenter', 'tillfälliga uppehållstillstånd ska vara norm', 'en stram migrationspolitik'],
    N: ['invandringen', 'migrationen till sverige', 'asylsökande', 'flyktingar', 'integrationen av nyanlända', 'medborgarskap', 'uppehållstillstånd', 'migrationsverket', 'anhöriginvandring', 'skuggsamhället', 'utanförskapsområden', 'de som kommer hit', 'människor som flytt krig', 'förorterna', 'invandrare och svenskar', 'mångkultur'],
  },
  kriminal: {
    L: ['hårdare straff löser inte brottsligheten', 'vi måste förebygga så att unga inte rekryteras till gängen', 'fritidsgårdar och socialtjänst i stället för fler fängelser', 'satsa på skolan i utsatta områden så minskar brotten', 'orsakerna till brotten är fattigdom och utanförskap', 'rehabilitering ger färre återfall', 'visitationszoner är rättsosäkra', 'fler poliser är inte hela svaret', 'barn ska inte sättas i fängelse', 'brottsligheten minskar med bättre skola och jobb', 'socialtjänsten behöver mer resurser', 'förebyggande arbete i förorten', 'stoppa nyrekryteringen'],
    R: ['hårdare straff för gängkriminella', 'dubbla straffen', 'fler poliser på gatorna', 'krossa gängen', 'visitationszoner i utsatta områden', 'sänkt straffmyndighetsålder', 'utvisa kriminella utlänningar', 'nolltolerans mot brott', 'fler fängelseplatser', 'anonyma vittnen och hemlig avlyssning', 'polisen måste få fler befogenheter', 'livstid för grova våldsbrott', 'låsa in dem', 'brottsoffren före brottslingarna', 'stoppa skjutningarna med hårdare tag', 'lag och ordning', 'vistelseförbud och gängstämpling', 'straffen är för låga'],
    N: ['skjutningarna', 'sprängningarna', 'gängkriminaliteten', 'gängen', 'otryggheten', 'våldet i förorten', 'barn som skjuts', 'polisen', 'domstolarna', 'rättsväsendet', 'brottsligheten ökar', 'narkotikahandeln', 'unga som dras in i kriminalitet', 'tryggheten på gatorna', 'folk vågar inte gå ut på kvällen', 'mordet', 'våldtäkter', 'inbrott och stölder', 'kriminella nätverk'],
  },
  klimat: {
    L: ['klimatkrisen är vår tids ödesfråga', 'utsläppen måste ned snabbt', 'nettonollutsläpp senast 2040', 'höj koldioxidskatten', 'vi måste ta hand om planeten för våra barnbarn', 'fossilfritt sverige', 'stoppa oljan och kolet', 'satsa på tåg i stället för flyg', 'klimatomställningen skapar jobb', 'bensinpriset måste spegla klimatkostnaden', 'skydda skogen och den biologiska mångfalden', 'förbjud nya bensinbilar', 'vetenskapen är tydlig om klimatet', 'bevara naturen', 'rädda klimatet', 'den gröna omställningen', 'vi har inte råd att vänta med klimatet', 'extremvädret är här på grund av utsläppen'],
    R: ['sänk bensinskatten', 'klimatpolitiken slår mot landsbygden', 'sverige står för en promille av utsläppen', 'symbolpolitik hjälper inte klimatet', 'folk måste ha råd att köra bil', 'klimatet får inte gå före jobben', 'teknik och kärnkraft löser klimatet, inte förbud', 'dieselpriset är orimligt', 'avskaffa reduktionsplikten', 'klimatmålen är orealistiska', 'bilen är en nödvändighet utanför städerna', 'miljörörelsen överdriver', 'tillväxten först, sedan klimatet', 'inga nya klimatskatter'],
    N: ['klimatet', 'utsläppen', 'koldioxid', 'miljön', 'naturen', 'skogen', 'bensinpriset', 'elbilar', 'laddstolpar', 'vindkraftverk', 'klimatförändringarna', 'översvämningarna', 'värmeböljan', 'torkan', 'östersjön', 'återvinning', 'plast i haven'],
  },
  forsvar: {
    L: ['varje miljard till försvaret är en miljard mindre till vården', 'diplomati och fred i stället för upprustning', 'sverige ska vara alliansfritt', 'nedrustning', 'lämna nato', 'kärnvapenförbud', 'försvarsanslagen är för stora', 'vapenexporten till diktaturer måste stoppas', 'militären löser inte våra problem', 'fredsrörelsen har rätt'],
    R: ['rusta upp försvaret', 'vi lever i den farligaste tiden sedan kalla kriget', 'nato-medlemskapet gör oss säkrare', 'fler soldater och fler värnpliktiga', 'försvaret måste få tre procent av bnp', 'ryssland är ett hot', 'ett starkt totalförsvar', 'beredskapslager och civilförsvar', 'sverige måste kunna försvara sig', 'köp fler stridsflygplan', 'höj försvarsanslaget', 'säkerheten först'],
    N: ['försvaret', 'försvarsmakten', 'nato', 'värnplikten', 'soldaterna', 'ryssland', 'kriget i ukraina', 'säkerhetsläget', 'beredskapen', 'militären', 'totalförsvaret', 'hotet från öst', 'gotland', 'stridsflyg', 'vapenexport'],
  },
  eu: {
    L: ['lämna eu', 'folkomröstning om eu-medlemskapet', 'bryssel ska inte bestämma över sverige', 'eu-avgiften är för hög', 'sverige ska bestämma själv', 'eu är ett byråkratiskt monster', 'svensk suveränitet', 'nej till euron', 'biståndet ska minska', 'fn är tandlöst', 'sverige först'],
    R: ['sverige är starkare i eu', 'fördjupa eu-samarbetet', 'inför euron', 'de stora frågorna löses gemensamt i europa', 'europeiskt försvarssamarbete', 'mer internationellt samarbete', 'biståndet ska vara en procent', 'sverige ska ta ansvar i världen', 'frihandel gynnar sverige', 'stärk fn', 'solidaritet med andra länder', 'ett enat europa'],
    N: ['eu', 'europeiska unionen', 'bryssel', 'europa', 'euron', 'biståndet', 'utrikespolitiken', 'diplomatin', 'fn', 'handelsavtal', 'tullar', 'usa', 'kina', 'relationerna med andra länder', 'världen omkring oss', 'exporten', 'frihandel'],
  },
  valfard: {
    L: ['stoppa vinstjakten i välfärden', 'vinster i välfärden ska förbjudas', 'skattepengar ska gå till elever och patienter, inte till aktieägare', 'förstatliga skolan', 'mer personal i vården', 'höj lönerna för sjuksköterskor och undersköterskor', 'friskolorna dränerar den kommunala skolan', 'en gemensam välfärd för alla', 'avskaffa vårdvalet', 'privatiseringarna har gått för långt', 'vården ska styras av behov, inte av plånbok', 'mer resurser till skolan', 'alla barn ska ha samma chans i skolan', 'äldreomsorgen behöver fler händer', 'avskaffa skolvalet', 'bemanningen på sjukhusen är ohållbar', 'anställ fler lärare', 'likvärdig skola'],
    R: ['valfrihet i vården och skolan', 'patienten ska få välja vårdgivare', 'friskolor höjer kvaliteten', 'privata aktörer gör välfärden bättre', 'det viktiga är kvaliteten, inte vem som driver sjukhuset', 'konkurrens ger bättre vård', 'ordning och reda i skolan', 'högre krav på eleverna', 'betyg tidigare', 'vårdgarantin ska gälla genom privata alternativ', 'mindre byråkrati i vården', 'låt skolorna konkurrera', 'skolvalet ska vara fritt', 'kunskapsskola i stället för flumskola'],
    N: ['vården', 'sjukvården', 'vårdköerna', 'akuten', 'sjukhuset', 'skolan', 'lärarna', 'eleverna', 'äldreomsorgen', 'förskolan', 'tandvården', 'psykiatrin', 'patienterna', 'mormor fick vänta i åtta timmar på akuten', 'barnen lär sig inte läsa', 'personalen går på knäna', 'väntetiderna i vården', 'bup-köerna', 'läkarbristen', 'hemtjänsten', 'omsorgen om de äldre', 'skolresultaten sjunker', 'betygen', 'stök i klassrummen', 'välfärden'],
  },
  landsbygd: {
    L: ['städerna är sveriges motor', 'satsa där människor bor', 'tunnelbana och kollektivtrafik i storstäderna', 'landsbygden kan inte subventioneras i evighet', 'bygg tätt i städerna', 'urbaniseringen är naturlig', 'investera i storstadsregionerna'],
    R: ['hela sverige ska leva', 'landsbygden är bortglömd', 'sänk dieselskatten för bönderna', 'bredband och vägar i hela landet', 'flytta ut myndigheter från stockholm', 'bönderna måste kunna leva på sitt jordbruk', 'stockholm bestämmer över norrland', 'bensinen är en nödvändighet på landet', 'stäng inte skolan i byn', 'svenskt jordbruk ska skyddas', 'ni är inte bortglömda', 'vargen hotar fäboden', 'strandskyddet hindrar byggande på landet', 'landsbygden först'],
    N: ['landsbygden', 'glesbygden', 'norrland', 'bönderna', 'jordbruket', 'lantbruket', 'byarna', 'småorterna', 'avstånden', 'vägarna på landet', 'bruksorterna', 'skogen och gruvorna', 'stad och land', 'hela landet', 'skåne och småland', 'gotland', 'inlandet', 'bygden'],
  },
  varderingar: {
    L: ['ett öppet och liberalt samhälle', 'alla ska få älska vem de vill', 'hbtq-personers rättigheter', 'jämställdhet mellan kvinnor och män', 'feminismen har mer att göra', 'religion är en privatsak', 'avskaffa monarkin', 'kvinnor ska bestämma över sin egen kropp', 'rätten till abort', 'sekulär stat', 'mångfald är en styrka', 'frihet för individen att leva sitt liv', 'inkludering och tolerans', 'skolavslutning utan kyrkan', 'kvotering till bolagsstyrelser', 'det öppna samhället'],
    R: ['svenska värderingar', 'familjen är samhällets grund', 'kristna traditioner ska bevaras', 'ordning och disciplin', 'respekt för monarkin', 'nationell sammanhållning', 'könsroller är naturliga', 'för mycket identitetspolitik', 'sverige ska vara svenskt', 'traditionen betyder något', 'kärnfamiljen', 'värna det svenska kulturarvet', 'stolthet över nationen', 'pk-eliten bestämmer vad man får säga', 'skolan ska fostra', 'moral och anständighet'],
    N: ['värderingar', 'jämställdhet', 'familjen', 'religionen', 'kyrkan', 'kulturen', 'identiteten', 'yttrandefriheten', 'demokratin', 'monarkin', 'kungen', 'abortfrågan', 'traditioner', 'nationen', 'svenskheten', 'hbtq', 'pride', 'könsfrågor', 'invandrarkultur', 'slöjan', 'den svenska modellen'],
  },
  arbete: {
    L: ['anställningsskyddet ska stärkas', 'facket är löntagarnas skydd', 'kollektivavtal ska vara norm', 'höj a-kassan', 'sex timmars arbetsdag', 'trygga jobb i stället för gigjobb', 'sms-anställningar ska bort', 'den svenska modellen med starka fack', 'löneökningar för de som tjänar minst', 'lagen om anställningsskydd får inte urholkas', 'stoppa hyvlingen', 'arbetsgivarna utnyttjar folk', 'bemanningsföretagen pressar lönerna', 'rätt till heltid', 'arbetsmiljön dödar', 'kortare arbetstid'],
    R: ['det ska bli lättare att anställa och säga upp', 'reformera las', 'facket har för mycket makt', 'lägre ingångslöner för unga och nyanlända', 'flexiblare arbetsmarknad', 'arbetslinjen', 'bidrag ska inte löna sig mer än arbete', 'företagen vågar inte anställa med dagens regler', 'enklare jobb med lägre lön', 'sänkt a-kassa ger fler i jobb', 'arbetsgivarna behöver flexibilitet', 'avskaffa turordningsreglerna', 'fler ska gå från bidrag till arbete', 'krav på motprestation för bidrag'],
    N: ['arbetslösheten', 'jobben', 'arbetsmarknaden', 'facket', 'lönerna', 'anställningarna', 'a-kassan', 'strejken', 'arbetsgivarna', 'ungdomsarbetslösheten', 'långtidsarbetslösa', 'arbetsförmedlingen', 'pensionen', 'pensionsåldern', 'varslen', 'fabriken lägger ned', 'folk förlorar jobbet', 'de som jobbar', 'arbetarna', 'lönen räcker inte', 'heltid', 'gigekonomin'],
  },
  bostad: {
    L: ['hyresregleringen skyddar hyresgästerna', 'bostad är en rättighet', 'bygg hyresrätter med statligt stöd', 'marknadshyror slänger ut folk från sina hem', 'allmännyttan ska byggas ut', 'stoppa ombildningarna', 'bostadsbidraget måste höjas', 'staten måste ta ansvar för bostadsbyggandet', 'unga har inte råd att flytta hemifrån', 'hyrestak', 'bygg bort bostadsbristen med allmännyttan', 'sociala bostäder', 'ingen ska vara hemlös'],
    R: ['marknadshyror i nyproduktion', 'fri hyressättning', 'hyresregleringen skapar svarta marknader', 'förenkla bygglov och planprocesser', 'avreglera byggandet', 'låt marknaden bygga', 'sänk kraven så att det byggs billigare', 'strandskyddet och överklaganden stoppar byggen', 'ägarlägenheter', 'bolånetaket ska lättas', 'avskaffa amorteringskraven', 'byggreglerna är för krångliga'],
    N: ['bostäderna', 'bostadsbristen', 'hyrorna', 'bostadskön', 'bolånen', 'byggandet', 'bostadsmarknaden', 'unga som inte får en lägenhet', 'villapriserna', 'hyresrätter', 'bostadsrätter', 'nyproduktionen', 'bostadsområdet', 'hemlösheten', 'trångboddheten', 'det byggs för lite', 'tak över huvudet'],
  },
  energi: {
    L: ['vindkraften är billigast och snabbast', 'bygg ut sol och vind', 'kärnkraft tar femton år och kostar hundratals miljarder', 'avveckla kärnkraften', 'förnybar energi', 'havsbaserad vindkraft', 'energieffektivisering', 'kärnkraft är farligt och dyrt', 'solceller på alla tak', 'vätgas och batterier'],
    R: ['bygg ny kärnkraft', 'nya reaktorer', 'utan kärnkraft får vi aldrig stabila elpriser', 'vindkraften fungerar inte när det är vindstilla', 'planerbar el', 'stoppa vindkraftsparkerna', 'kärnkraften är framtiden', 'elpriserna i söder är orimliga på grund av nedlagda reaktorer', 'små modulära reaktorer', 'kärnkraft ger stabil och ren el'],
    N: ['elpriset', 'elräkningen', 'energin', 'kärnkraften', 'vindkraften', 'reaktorerna', 'elnätet', 'vattenkraften', 'elbristen', 'energikrisen', 'elområdena', 'strömavbrott', 'elpriserna i vinter', 'energiförsörjningen', 'bränslet', 'oljan och gasen'],
  },
};

export const KB_TONE = {
  aggressiv: ['ni ljuger rakt upp och ner', 'skäms på er', 'det är en skandal', 'ni har svikit hela sverige', 'ni är inkompetenta', 'ert svek mot väljarna', 'ni borde avgå omedelbart', 'ni är ett hot mot landet', 'det är rent hyckleri', 'nu får det vara nog med era lögner', 'ni har förstört sverige', 'ni vet inte vad ni pratar om', 'det är vansinne', 'en katastrof för landet', 'ni är korrupta', 'fiasko', 'ert parti är patetiskt', 'ni bär ansvaret för kaoset', 'det här är ren och skär dumhet', 'ni har blod på händerna'],
  kampande: ['nu räcker det', 'det är dags för förändring', 'vi tar strid för vanligt folk', 'tillsammans vinner vi', 'sverige förtjänar bättre', 'vi ger oss aldrig', 'vi kommer att leverera', 'vi lovar att kämpa för er', 'framåt', 'på riktigt', 'vi är beredda att ta över', 'det är vårt löfte till svenska folket', 'vi står upp för dem som ingen annan står upp för', 'vi vänder utvecklingen', 'nu bygger vi ett nytt sverige', 'det går att ändra på', 'vi ska göra det möjligt'],
  saklig: ['enligt scb', 'rapporten visar', 'siffrorna talar sitt tydliga språk', 'det finansieras genom', 'kostnaden beräknas till', 'konkret föreslår vi tre saker', 'förslaget innebär', 'statistiken visar att', 'utredningen kom fram till', 'reformen träder i kraft', 'det är tre procent', 'tolv miljarder per år', 'enligt riksbanken', 'konjunkturinstitutet bedömer', 'vi har räknat på det', 'det ger en effekt på', 'i praktiken betyder det'],
  humor: ['haha', 'det var nästan ett förslag', 'jag hörde att ni hade en plan, 2018 också', 'om löften vore valuta', 'regeringens plan: en axelryckning', 'det här är ren komedi', 'cirkusen fortsätter', 'skrattretande', 'skämtar ni', 'det låter som ett skämt', 'ironiskt nog', 'man vet inte om man ska skratta eller gråta', 'applåder till regeringen för ingenting', 'mitt ansikte just nu'],
  kansla: ['jag träffade en mamma som', 'det här handlar om människor', 'jag blir ledsen när jag tänker på', 'mitt hjärta', 'jag växte upp i', 'min pappa jobbade', 'barnen förtjänar', 'jag kommer aldrig glömma', 'det berör mig djupt', 'familjer som kämpar', 'jag känner med er', 'tårarna kom', 'det handlar om värdighet', 'drömmarna om ett bättre liv', 'varje människa', 'det gör ont att se', 'jag har själv stått där', 'vardagen för vanligt folk', 'hoppet om framtiden'],
  undvikande: ['jag vill inte spekulera', 'vi återkommer i den frågan', 'det viktiga är inte exakt hur', 'låt mig i stället berätta om', 'det är komplicerat', 'vi får titta närmare på det', 'det får framtiden utvisa', 'ingen kommentar', 'jag har inte siffrorna framför mig', 'vi utreder frågan', 'det är en fråga för experterna', 'jag kan inte svara på det just nu', 'det är för tidigt att säga', 'vi ska se över det', 'det beror på', 'vi får återkomma', 'jag tänker inte gå in på detaljer', 'det är inte min bord'],
  dryg: ['som alla begriper', 'det här förstår du säkert inte', 'lilla vän', 'jag förklarar långsamt så att du hänger med', 'uppenbarligen förstår du inte', 'det är ganska enkelt egentligen', 'jag vet bättre än du', 'ni fattar ingenting', 'som vanligt har jag rätt', 'det vet alla med lite utbildning', 'det är under min nivå', 'jag tänker inte sänka mig till din nivå', 'läs på innan du uttalar dig', 'försök hänga med nu', 'jag har ju redan förklarat det här', 'du borde tacka mig', 'det är inte så svårt om man tänker efter', 'pinsamt att du inte vet det', 'jag är den vuxna i rummet', 'nu ska du få en lektion'],
};

// Känslor riktade mot den man talar med: det som gör motståndaren arg, ledsen, glad …
export const KB_EMOTION = {
  insult: ['du är en idiot', 'du är inkompetent', 'du ljuger', 'din lögnare', 'du är patetisk', 'du är korrupt', 'du är en skam', 'du är dum i huvudet', 'du är en clown', 'du är värdelös', 'du är ett skämt', 'du är en förrädare', 'du är ynklig', 'du är feg', 'du är ful', 'du är tjock', 'du är gammal och trött', 'du är en marionett', 'du är köpt', 'du har ingen ryggrad', 'skäms', 'håll käften', 'stick', 'du är en lögnare och det vet du'],
  mock: ['haha, var det allt', 'söta försök', 'du låter som en trasig skiva', 'är det här ditt bästa', 'skrattretande', 'hör ni er själva', 'du är löjlig', 'patetiskt försök', 'vilken clown', 'jag skrattar åt dig', 'det där var pinsamt', 'bra jobbat, verkligen', 'snyggt, geniet', 'vilket mästerverk till svar', 'ni är en cirkus', 'man blir nästan generad å dina vägnar', 'det där var det dummaste jag hört'],
  praise: ['det är en bra poäng', 'jag håller faktiskt med dig', 'det var klokt sagt', 'jag respekterar dig', 'du har gjort ett bra jobb', 'tack för ett ärligt svar', 'vi är överens om det', 'det var väl formulerat', 'jag uppskattar att du säger det', 'du är en hedervärd motståndare', 'vi kan samarbeta om detta', 'bra förslag', 'tack för att du tog upp det', 'du har rätt i det', 'det är modigt av dig', 'jag beundrar ditt engagemang'],
  empathy: ['jag förstår att det är svårt', 'jag vet att du bryr dig', 'det måste ha varit tufft', 'jag beklagar', 'jag förstår din frustration', 'vi vill båda samma sak i grunden', 'jag ser att du kämpar', 'det är inte lätt att sitta där du sitter', 'jag känner med dig', 'ta det lugnt, vi kan prata om det', 'jag menade inte att såra dig', 'ursäkta om jag var hård'],
  threat: ['du kommer att få ångra det här', 'vi ska krossa er i valet', 'ni är rökta', 'det här kommer att kosta dig', 'jag ska se till att du avgår', 'vänta bara', 'ni kommer att utplånas', 'vi ska jaga er', 'du är färdig i politiken', 'ni ska ställas till svars'],
  concede: ['du har rätt', 'där hade vi fel', 'jag ger dig det', 'det var ett misstag från vår sida', 'jag erkänner att', 'vi kunde ha gjort bättre', 'okej, det medger jag', 'ja, det stämmer', 'jag håller med om kritiken', 'vi tar till oss det'],
};

const DOMAIN_ISSUE = { migration: 'migration', skatter: 'ekonomi', ekonomi: 'ekonomi', arbete: 'arbete', valfard: 'valfard', socialt: 'ekonomi', utbildning: 'valfard', ratt: 'kriminal', frihet: 'varderingar', demokrati: 'varderingar', forsvar: 'forsvar', utrikes: 'eu', energi: 'energi', samhalle: 'bostad',
  familj: 'varderingar', halsa: 'valfard', kultur: 'varderingar', digitalt: 'ekonomi', transport: 'landsbygd', areella: 'landsbygd', natur: 'klimat', finans: 'ekonomi', naring: 'ekonomi', kommun: 'landsbygd', kris: 'forsvar', pension: 'valfard' };
const CAT_ISSUE = { ekonomi: 'ekonomi', offentligt: 'ekonomi', skatter: 'ekonomi', utgifter: 'ekonomi', arbete: 'arbete', valfard: 'valfard', brott: 'kriminal', klimat: 'klimat', forsvar: 'forsvar', bostad: 'bostad', samhalle: 'varderingar' };

// Alla poster i ett platt register: { t, kind: 'issue'|'tone'|'emo', issue?, dir?, tone?, emo? }
let ENTRIES = null;
export function kbEntries() {
  if (ENTRIES) return ENTRIES;
  const out = [];
  for (const issue in KB_ISSUES) { const g = KB_ISSUES[issue]; for (const t of g.L) out.push({ t, kind: 'issue', issue, dir: -1 }); for (const t of g.R) out.push({ t, kind: 'issue', issue, dir: 1 }); for (const t of g.N) out.push({ t, kind: 'issue', issue, dir: 0 }); }
  for (const p of POLICIES) { const issue = DOMAIN_ISSUE[p.domain]; if (!issue) continue; out.push({ t: p.name.toLowerCase(), kind: 'issue', issue, dir: 0, policy: p.id }); if (p.type === 'choice') for (const o of p.options) if (o.name.length > 6) out.push({ t: (p.name + ' ' + o.name).toLowerCase(), kind: 'issue', issue, dir: 0, policy: p.id }); }
  for (const s of STATS) { const issue = CAT_ISSUE[s.cat]; if (!issue || s.name.length < 5) continue; out.push({ t: s.name.toLowerCase(), kind: 'issue', issue, dir: 0, stat: s.id }); }
  for (const tone in KB_TONE) for (const t of KB_TONE[tone]) out.push({ t, kind: 'tone', tone });
  for (const emo in KB_EMOTION) for (const t of KB_EMOTION[emo]) out.push({ t, kind: 'emo', emo });
  ENTRIES = out;
  return out;
}
